name: Deploy webgpu-profiler to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy website to Cloud Run
    uses: ./.github/workflows/deploy-service.yml
    with:
      service_name: webgpu-profiler
      dockerfile: packages/website/Dockerfile
      context: .
    secrets:
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
